name: Chroot Kinux

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  chroot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          mkdir -p kinux-fs
          sudo tar -xJf kinux-rootfs.tar.xz -C kinux-fs
          ls -la kinux-fs/usr/local/bin/
          file kinux-fs/usr/local/bin/oils-for-unix
          file kinux-fs/bin/busybox
